#!/usr/bin/env bash
# Configures a new Ubuntu machine to respect certain requirements

#!/usr/bin/env bash
# Configures a new Ubuntu machine to respect certain requirements

sudo apt-get update
sudo apt-get install nginx
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
