#!/usr/bin/env bash
# Configures a new Ubuntu machine to respect certain requirements

#!/usr/bin/env bash
# Configures a new Ubuntu machine to respect certain requirements

sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
