#!/usr/bin/env bash
# This script ensures each server responds with a custom header

sudo apt-get update
sudo apt-get install nginx
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart

nginx_conf="/etc/nginx/nginx.conf"

sudo sed -i '29a add_header X-Served-By $hostname;' $nginx_conf
sudo service nginx restart
