#!/usr/bin/env bash
# Configueres haproxy on the load balancing server

sudo apt-get update
sudo apt-get -y install haproxy

echo "
frontend my_frontend
\tbind*:80
\tmode http

\tdefault_backend my_backend

backend my_backend
\tmode http
\tbalance roundrobin
\tserver server1 54.146.81.93 check
\tserver server2 34.232.76.218:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo systemctl stop nginx
sudo systemctl restart haproxy
