#!/usr/bin/env bash
# Fixes the problem

sudo apt-get update
sudo apt-get install nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
