#!/usr/bin/env bash
# Fixes the problem

cd /etc/nginx/sites-enabled/ || exit;
# Delete the default file
rm default;
# Create symbolic link to the deafult file in sites-available
ln -s /etc/nginx/sites-available/default default;
# Restart Nginx
service nginx restart
