#!/usr/bin/env bash
# Changes the default user and changes the default server port to 8080

useradd -G sudo nginx
chmod 644 /etc/nginx/nginx.conf
sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i 's/[:]?80 /8080 /g' /etc/nginx/sites-available/default
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default;
sudo -u nginx service nginx restart
